version: '3'

services:

  http:
    container_name: app-bundle
    build:
        context: .
    image: appbundle:config
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
